---
- name: Install Httpd
  package:
    name: httpd
    state: present

- name: Start Httpd
  service:
    name: httpd
    state: started

- name: Enabled Httpd
  service:
    name: httpd
    enabled: yes  
